GET http://localhost:5000/getData/2a5ae8c1d14a8cb5f83f9bcfbd191ef7 HTTP/1.1
content-type: application/json

{
    "trapID":"123",
    "path":"C:\\Users\\jerry\\Documents\\GitHub\\NewServer\\newML\\runs\\detect\\exp4\\alee.jpg"
}