GET http://localhost:5000/traps/0cc175b9c0f1b6a831c399e269772661 HTTP/1.1
content-type: application/json

{
    "trapID":"123",
    "path":"C:\\Users\\jerry\\Documents\\GitHub\\NewServer\\newML\\runs\\detect\\exp4\\alee.jpg"
}