const entry = require('./entry')
const getImage = require('./getImage')
const postImage = require('./postImage')
const addTrap = require('./addTrap')
const getTrap = require('./getTraps')
const insertTempreture = require('./insertTempreture')
const login = require('./login')
const register = require('./register')
module.exports = {entry,getImage,postImage,addTrap,getTrap,insertTempreture,login,register}